-- This file was generated by a python script on 2024-09-26

local masks = {}
local curved_rail = {}
local straight_rail = {}

-- ======================================
straight_rail[0] = {}
straight_rail[0][ 8] = {{pos={x=-8, y= 0}, o=false},{pos={x=-8, y=-1}, o=false}}
straight_rail[0][ 7] = {{pos={x=-7, y= 0}, o=false},{pos={x=-7, y=-1}, o=false}}
straight_rail[0][ 6] = {{pos={x=-6, y= 0}, o=false},{pos={x=-6, y=-1}, o=false}}
straight_rail[0][ 5] = {{pos={x=-5, y= 0}, o=false},{pos={x=-5, y=-1}, o=false}}
straight_rail[0][ 4] = {{pos={x=-4, y= 0}, o=false},{pos={x=-4, y=-1}, o=false}}
straight_rail[0][ 3] = {{pos={x=-3, y= 0}, o=false},{pos={x=-3, y=-1}, o=false}}
straight_rail[0][ 2] = {{pos={x=-2, y= 0}, o=false},{pos={x=-2, y=-1}, o=false}}
straight_rail[0][ 1] = {{pos={x=-1, y= 0}, o=false},{pos={x=-1, y=-1}, o=false}}
straight_rail[0][-1] = {{pos={x= 0, y= 0}, o=false},{pos={x= 0, y=-1}, o=false}}
straight_rail[0][-2] = {{pos={x= 1, y= 0}, o=false},{pos={x= 1, y=-1}, o=false}}
straight_rail[0][-3] = {{pos={x= 2, y= 0}, o=false},{pos={x= 2, y=-1}, o=false}}
straight_rail[0][-4] = {{pos={x= 3, y= 0}, o=false},{pos={x= 3, y=-1}, o=false}}
straight_rail[0][-5] = {{pos={x= 4, y= 0}, o=false},{pos={x= 4, y=-1}, o=false}}
straight_rail[0][-6] = {{pos={x= 5, y= 0}, o=false},{pos={x= 5, y=-1}, o=false}}
straight_rail[0][-7] = {{pos={x= 6, y= 0}, o=false},{pos={x= 6, y=-1}, o=false}}
straight_rail[0][-8] = {{pos={x= 7, y= 0}, o=false},{pos={x= 7, y=-1}, o=false}}
-- ======================================
straight_rail[2] = {}
straight_rail[2][ 8] = {{pos={x=-1, y=-8}, o=false},{pos={x= 0, y=-8}, o=false}}
straight_rail[2][ 7] = {{pos={x=-1, y=-7}, o=false},{pos={x= 0, y=-7}, o=false}}
straight_rail[2][ 6] = {{pos={x=-1, y=-6}, o=false},{pos={x= 0, y=-6}, o=false}}
straight_rail[2][ 5] = {{pos={x=-1, y=-5}, o=false},{pos={x= 0, y=-5}, o=false}}
straight_rail[2][ 4] = {{pos={x=-1, y=-4}, o=false},{pos={x= 0, y=-4}, o=false}}
straight_rail[2][ 3] = {{pos={x=-1, y=-3}, o=false},{pos={x= 0, y=-3}, o=false}}
straight_rail[2][ 2] = {{pos={x=-1, y=-2}, o=false},{pos={x= 0, y=-2}, o=false}}
straight_rail[2][ 1] = {{pos={x=-1, y=-1}, o=false},{pos={x= 0, y=-1}, o=false}}
straight_rail[2][-1] = {{pos={x=-1, y= 0}, o=false},{pos={x= 0, y= 0}, o=false}}
straight_rail[2][-2] = {{pos={x=-1, y= 1}, o=false},{pos={x= 0, y= 1}, o=false}}
straight_rail[2][-3] = {{pos={x=-1, y= 2}, o=false},{pos={x= 0, y= 2}, o=false}}
straight_rail[2][-4] = {{pos={x=-1, y= 3}, o=false},{pos={x= 0, y= 3}, o=false}}
straight_rail[2][-5] = {{pos={x=-1, y= 4}, o=false},{pos={x= 0, y= 4}, o=false}}
straight_rail[2][-6] = {{pos={x=-1, y= 5}, o=false},{pos={x= 0, y= 5}, o=false}}
straight_rail[2][-7] = {{pos={x=-1, y= 6}, o=false},{pos={x= 0, y= 6}, o=false}}
straight_rail[2][-8] = {{pos={x=-1, y= 7}, o=false},{pos={x= 0, y= 7}, o=false}}
-- ======================================
straight_rail[1] = {}
straight_rail[1][ 8] = {{pos={x=-5, y= 4}, o=false},{pos={x=-5, y= 5}, o= true},{pos={x=-6, y= 4}, o= true}}
straight_rail[1][ 7] = {{pos={x=-4, y= 4}, o= true},{pos={x=-5, y= 3}, o= true}}
straight_rail[1][ 6] = {{pos={x=-4, y= 3}, o=false}}
straight_rail[1][ 5] = {{pos={x=-3, y= 2}, o=false},{pos={x=-3, y= 3}, o= true},{pos={x=-4, y= 2}, o= true}}
straight_rail[1][ 4] = {{pos={x=-2, y= 2}, o= true},{pos={x=-3, y= 1}, o= true}}
straight_rail[1][ 3] = {{pos={x=-1, y= 1}, o= true},{pos={x=-2, y= 0}, o= true},{pos={x=-2, y= 1}, o=false}}
straight_rail[1][ 2] = {{pos={x=-1, y= 0}, o=false}}
straight_rail[1][ 1] = {{pos={x= 0, y=-1}, o=false},{pos={x= 0, y= 0}, o= true},{pos={x=-1, y=-1}, o= true}}
straight_rail[1][-1] = {{pos={x= 1, y=-1}, o= true},{pos={x= 0, y=-2}, o= true}}
straight_rail[1][-2] = {{pos={x= 1, y=-2}, o=false}}
straight_rail[1][-3] = {{pos={x= 2, y=-3}, o=false},{pos={x= 2, y=-2}, o= true},{pos={x= 1, y=-3}, o= true}}
straight_rail[1][-4] = {{pos={x= 3, y=-3}, o= true},{pos={x= 2, y=-4}, o= true}}
straight_rail[1][-5] = {{pos={x= 4, y=-4}, o= true},{pos={x= 3, y=-5}, o= true},{pos={x= 3, y=-4}, o=false}}
straight_rail[1][-6] = {{pos={x= 4, y=-5}, o=false}}
straight_rail[1][-7] = {{pos={x= 5, y=-5}, o= true},{pos={x= 4, y=-6}, o= true}}
straight_rail[1][-8] = {{pos={x= 6, y=-6}, o= true},{pos={x= 5, y=-7}, o= true},{pos={x= 5, y=-6}, o=false}}
-- ======================================
straight_rail[3] = {}
straight_rail[3][ 8] = {{pos={x=-5, y=-5}, o=false},{pos={x=-6, y=-5}, o= true},{pos={x=-5, y=-6}, o= true}}
straight_rail[3][ 7] = {{pos={x=-5, y=-4}, o= true},{pos={x=-4, y=-5}, o= true}}
straight_rail[3][ 6] = {{pos={x=-4, y=-4}, o=false}}
straight_rail[3][ 5] = {{pos={x=-3, y=-3}, o=false},{pos={x=-4, y=-3}, o= true},{pos={x=-3, y=-4}, o= true}}
straight_rail[3][ 4] = {{pos={x=-3, y=-2}, o= true},{pos={x=-2, y=-3}, o= true}}
straight_rail[3][ 3] = {{pos={x=-2, y=-1}, o= true},{pos={x=-1, y=-2}, o= true},{pos={x=-2, y=-2}, o=false}}
straight_rail[3][ 2] = {{pos={x=-1, y=-1}, o=false}}
straight_rail[3][ 1] = {{pos={x= 0, y= 0}, o=false},{pos={x=-1, y= 0}, o= true},{pos={x= 0, y=-1}, o= true}}
straight_rail[3][-1] = {{pos={x= 0, y= 1}, o= true},{pos={x= 1, y= 0}, o= true}}
straight_rail[3][-2] = {{pos={x= 1, y= 1}, o=false}}
straight_rail[3][-3] = {{pos={x= 2, y= 2}, o=false},{pos={x= 1, y= 2}, o= true},{pos={x= 2, y= 1}, o= true}}
straight_rail[3][-4] = {{pos={x= 2, y= 3}, o= true},{pos={x= 3, y= 2}, o= true}}
straight_rail[3][-5] = {{pos={x= 3, y= 4}, o= true},{pos={x= 4, y= 3}, o= true},{pos={x= 3, y= 3}, o=false}}
straight_rail[3][-6] = {{pos={x= 4, y= 4}, o=false}}
straight_rail[3][-7] = {{pos={x= 4, y= 5}, o= true},{pos={x= 5, y= 4}, o= true}}
straight_rail[3][-8] = {{pos={x= 5, y= 6}, o= true},{pos={x= 6, y= 5}, o= true},{pos={x= 5, y= 5}, o=false}}
-- ======================================
straight_rail[5] = {}
straight_rail[5][ 8] = {{pos={x= 4, y=-5}, o=false},{pos={x= 4, y=-6}, o= true},{pos={x= 5, y=-5}, o= true}}
straight_rail[5][ 7] = {{pos={x= 3, y=-5}, o= true},{pos={x= 4, y=-4}, o= true}}
straight_rail[5][ 6] = {{pos={x= 3, y=-4}, o=false}}
straight_rail[5][ 5] = {{pos={x= 2, y=-3}, o=false},{pos={x= 2, y=-4}, o= true},{pos={x= 3, y=-3}, o= true}}
straight_rail[5][ 4] = {{pos={x= 1, y=-3}, o= true},{pos={x= 2, y=-2}, o= true}}
straight_rail[5][ 3] = {{pos={x= 0, y=-2}, o= true},{pos={x= 1, y=-1}, o= true},{pos={x= 1, y=-2}, o=false}}
straight_rail[5][ 2] = {{pos={x= 0, y=-1}, o=false}}
straight_rail[5][ 1] = {{pos={x=-1, y= 0}, o=false},{pos={x=-1, y=-1}, o= true},{pos={x= 0, y= 0}, o= true}}
straight_rail[5][-1] = {{pos={x=-2, y= 0}, o= true},{pos={x=-1, y= 1}, o= true}}
straight_rail[5][-2] = {{pos={x=-2, y= 1}, o=false}}
straight_rail[5][-3] = {{pos={x=-3, y= 2}, o=false},{pos={x=-3, y= 1}, o= true},{pos={x=-2, y= 2}, o= true}}
straight_rail[5][-4] = {{pos={x=-4, y= 2}, o= true},{pos={x=-3, y= 3}, o= true}}
straight_rail[5][-5] = {{pos={x=-5, y= 3}, o= true},{pos={x=-4, y= 4}, o= true},{pos={x=-4, y= 3}, o=false}}
straight_rail[5][-6] = {{pos={x=-5, y= 4}, o=false}}
straight_rail[5][-7] = {{pos={x=-6, y= 4}, o= true},{pos={x=-5, y= 5}, o= true}}
straight_rail[5][-8] = {{pos={x=-7, y= 5}, o= true},{pos={x=-6, y= 6}, o= true},{pos={x=-6, y= 5}, o=false}}
-- ======================================
straight_rail[7] = {}
straight_rail[7][ 8] = {{pos={x= 4, y= 4}, o=false},{pos={x= 5, y= 4}, o= true},{pos={x= 4, y= 5}, o= true}}
straight_rail[7][ 7] = {{pos={x= 4, y= 3}, o= true},{pos={x= 3, y= 4}, o= true}}
straight_rail[7][ 6] = {{pos={x= 3, y= 3}, o=false}}
straight_rail[7][ 5] = {{pos={x= 2, y= 2}, o=false},{pos={x= 3, y= 2}, o= true},{pos={x= 2, y= 3}, o= true}}
straight_rail[7][ 4] = {{pos={x= 2, y= 1}, o= true},{pos={x= 1, y= 2}, o= true}}
straight_rail[7][ 3] = {{pos={x= 1, y= 0}, o= true},{pos={x= 0, y= 1}, o= true},{pos={x= 1, y= 1}, o=false}}
straight_rail[7][ 2] = {{pos={x= 0, y= 0}, o=false}}
straight_rail[7][ 1] = {{pos={x=-1, y=-1}, o=false},{pos={x= 0, y=-1}, o= true},{pos={x=-1, y= 0}, o= true}}
straight_rail[7][-1] = {{pos={x=-1, y=-2}, o= true},{pos={x=-2, y=-1}, o= true}}
straight_rail[7][-2] = {{pos={x=-2, y=-2}, o=false}}
straight_rail[7][-3] = {{pos={x=-3, y=-3}, o=false},{pos={x=-2, y=-3}, o= true},{pos={x=-3, y=-2}, o= true}}
straight_rail[7][-4] = {{pos={x=-3, y=-4}, o= true},{pos={x=-4, y=-3}, o= true}}
straight_rail[7][-5] = {{pos={x=-4, y=-5}, o= true},{pos={x=-5, y=-4}, o= true},{pos={x=-4, y=-4}, o=false}}
straight_rail[7][-6] = {{pos={x=-5, y=-5}, o=false}}
straight_rail[7][-7] = {{pos={x=-5, y=-6}, o= true},{pos={x=-6, y=-5}, o= true}}
straight_rail[7][-8] = {{pos={x=-6, y=-7}, o= true},{pos={x=-7, y=-6}, o= true},{pos={x=-6, y=-6}, o=false}}
-- ======================================
curved_rail[0] = {}
curved_rail[0][8] = {
    {pos={x= 3, y=-9}, o= true}, {pos={x= 3, y=-8}, o=false}, {pos={x= 4, y=-8}, o=false},
    {pos={x= 4, y=-7}, o=false}, {pos={x= 5, y=-7}, o=false}, {pos={x= 5, y=-6}, o=false},
    {pos={x= 6, y=-5}, o=false}, {pos={x= 6, y=-4}, o=false}, {pos={x= 7, y=-3}, o=false},
    {pos={x= 7, y=-2}, o=false}, {pos={x= 7, y=-1}, o=false}, {pos={x= 8, y= 0}, o=false},
    {pos={x= 8, y= 1}, o=false}, {pos={x= 8, y= 2}, o=false}, {pos={x= 8, y= 3}, o=false}}
curved_rail[0][7] = {
    {pos={x= 2, y=-8}, o= true}, {pos={x= 3, y=-7}, o=false}, {pos={x= 4, y=-6}, o=false},
    {pos={x= 4, y=-5}, o=false}, {pos={x= 5, y=-5}, o=false}, {pos={x= 5, y=-4}, o=false},
    {pos={x= 6, y=-3}, o=false}, {pos={x= 6, y=-2}, o=false}, {pos={x= 6, y=-1}, o=false},
    {pos={x= 7, y= 0}, o=false}, {pos={x= 7, y= 1}, o=false}, {pos={x= 7, y= 2}, o=false},
    {pos={x= 7, y= 3}, o=false}}
curved_rail[0][6] = {
    {pos={x= 2, y=-7}, o=false}, {pos={x= 2, y=-6}, o=false}, {pos={x= 3, y=-6}, o=false},
    {pos={x= 3, y=-5}, o=false}, {pos={x= 4, y=-4}, o=false}, {pos={x= 4, y=-3}, o=false},
    {pos={x= 5, y=-3}, o=false}, {pos={x= 5, y=-2}, o=false}, {pos={x= 5, y=-1}, o=false},
    {pos={x= 6, y= 0}, o=false}, {pos={x= 6, y= 1}, o=false}, {pos={x= 6, y= 2}, o=false},
    {pos={x= 6, y= 3}, o=false}}
curved_rail[0][5] = {
    {pos={x= 1, y=-7}, o= true}, {pos={x= 1, y=-6}, o=false}, {pos={x= 2, y=-5}, o=false},
    {pos={x= 3, y=-4}, o=false}, {pos={x= 3, y=-3}, o=false}, {pos={x= 4, y=-2}, o=false},
    {pos={x= 4, y=-1}, o=false}, {pos={x= 5, y= 0}, o=false}, {pos={x= 5, y= 1}, o=false},
    {pos={x= 5, y= 2}, o=false}, {pos={x= 5, y= 3}, o=false}}
curved_rail[0][4] = {
    {pos={x= 0, y=-6}, o= true}, {pos={x= 1, y=-5}, o=false}, {pos={x= 2, y=-4}, o=false},
    {pos={x= 2, y=-3}, o=false}, {pos={x= 3, y=-2}, o=false}, {pos={x= 3, y=-1}, o=false},
    {pos={x= 4, y= 0}, o=false}, {pos={x= 4, y= 1}, o=false}, {pos={x= 4, y= 2}, o=false},
    {pos={x= 4, y= 3}, o=false}}
curved_rail[0][3] = {
    {pos={x=-1, y=-5}, o= true}, {pos={x= 0, y=-5}, o=false}, {pos={x= 0, y=-4}, o=false},
    {pos={x= 1, y=-4}, o=false}, {pos={x= 1, y=-3}, o=false}, {pos={x= 2, y=-2}, o=false},
    {pos={x= 2, y=-1}, o=false}, {pos={x= 2, y= 0}, o=false}, {pos={x= 3, y= 0}, o=false},
    {pos={x= 3, y= 1}, o=false}, {pos={x= 3, y= 2}, o=false}, {pos={x= 3, y= 3}, o=false}}
curved_rail[0][2] = {
    {pos={x=-1, y=-4}, o=false}, {pos={x= 0, y=-3}, o=false}, {pos={x= 0, y=-2}, o=false},
    {pos={x= 1, y=-2}, o=false}, {pos={x= 1, y=-1}, o=false}, {pos={x= 1, y= 0}, o=false},
    {pos={x= 2, y= 1}, o=false}, {pos={x= 2, y= 2}, o=false}, {pos={x= 2, y= 3}, o=false}}
curved_rail[0][1] = {
    {pos={x=-2, y=-4}, o= true}, {pos={x=-2, y=-3}, o=false}, {pos={x=-1, y=-3}, o=false},
    {pos={x=-1, y=-2}, o=false}, {pos={x= 0, y=-1}, o=false}, {pos={x= 0, y= 0}, o=false},
    {pos={x= 1, y= 1}, o=false}, {pos={x= 1, y= 2}, o=false}, {pos={x= 1, y= 3}, o=false}}
curved_rail[0][-1] = {
    {pos={x=-3, y=-3}, o= true}, {pos={x=-2, y=-2}, o=false}, {pos={x=-1, y=-1}, o=false},
    {pos={x=-1, y= 0}, o=false}, {pos={x= 0, y= 1}, o=false}, {pos={x= 0, y= 2}, o=false},
    {pos={x= 0, y= 3}, o=false}}
curved_rail[0][-2] = {
    {pos={x=-3, y=-2}, o=false}, {pos={x=-2, y=-1}, o=false}, {pos={x=-2, y= 0}, o=false},
    {pos={x=-1, y= 1}, o=false}, {pos={x=-1, y= 2}, o=false}, {pos={x=-1, y= 3}, o=false}}
curved_rail[0][-3] = {
    {pos={x=-4, y=-2}, o= true}, {pos={x=-4, y=-1}, o=false}, {pos={x=-3, y=-1}, o=false},
    {pos={x=-3, y= 0}, o=false}, {pos={x=-2, y= 1}, o=false}, {pos={x=-2, y= 2}, o=false},
    {pos={x=-2, y= 3}, o=false}}
curved_rail[0][-4] = {
    {pos={x=-5, y=-1}, o= true}, {pos={x=-4, y= 0}, o=false}, {pos={x=-4, y= 1}, o=false},
    {pos={x=-3, y= 1}, o=false}, {pos={x=-3, y= 2}, o=false}, {pos={x=-3, y= 3}, o=false}}
curved_rail[0][-5] = {
    {pos={x=-6, y= 0}, o= true}, {pos={x=-5, y= 0}, o=false}, {pos={x=-5, y= 1}, o=false},
    {pos={x=-4, y= 2}, o=false}, {pos={x=-4, y= 3}, o=false}}
curved_rail[0][-6] = {
    {pos={x=-6, y= 1}, o=false}, {pos={x=-5, y= 2}, o=false}, {pos={x=-5, y= 3}, o=false}}
curved_rail[0][-7] = {
    {pos={x=-7, y= 1}, o= true}, {pos={x=-6, y= 2}, o=false}, {pos={x=-6, y= 3}, o=false}}
curved_rail[0][-8] = {
    {pos={x=-8, y= 2}, o= true}, {pos={x=-7, y= 2}, o=false}, {pos={x=-7, y= 3}, o=false}}
-- ======================================
curved_rail[1] = {}
curved_rail[1][8] = {
    {pos={x= 7, y= 2}, o= true}, {pos={x= 6, y= 2}, o=false}, {pos={x= 6, y= 3}, o=false}}
curved_rail[1][7] = {
    {pos={x= 6, y= 1}, o= true}, {pos={x= 5, y= 2}, o=false}, {pos={x= 5, y= 3}, o=false}}
curved_rail[1][6] = {
    {pos={x= 5, y= 1}, o=false}, {pos={x= 4, y= 2}, o=false}, {pos={x= 4, y= 3}, o=false}}
curved_rail[1][5] = {
    {pos={x= 5, y= 0}, o= true}, {pos={x= 4, y= 0}, o=false}, {pos={x= 4, y= 1}, o=false},
    {pos={x= 3, y= 2}, o=false}, {pos={x= 3, y= 3}, o=false}}
curved_rail[1][4] = {
    {pos={x= 4, y=-1}, o= true}, {pos={x= 3, y= 0}, o=false}, {pos={x= 3, y= 1}, o=false},
    {pos={x= 2, y= 1}, o=false}, {pos={x= 2, y= 2}, o=false}, {pos={x= 2, y= 3}, o=false}}
curved_rail[1][3] = {
    {pos={x= 3, y=-2}, o= true}, {pos={x= 3, y=-1}, o=false}, {pos={x= 2, y=-1}, o=false},
    {pos={x= 2, y= 0}, o=false}, {pos={x= 1, y= 1}, o=false}, {pos={x= 1, y= 2}, o=false},
    {pos={x= 1, y= 3}, o=false}}
curved_rail[1][2] = {
    {pos={x= 2, y=-2}, o=false}, {pos={x= 1, y=-1}, o=false}, {pos={x= 1, y= 0}, o=false},
    {pos={x= 0, y= 1}, o=false}, {pos={x= 0, y= 2}, o=false}, {pos={x= 0, y= 3}, o=false}}
curved_rail[1][1] = {
    {pos={x= 2, y=-3}, o= true}, {pos={x= 1, y=-2}, o=false}, {pos={x= 0, y=-1}, o=false},
    {pos={x= 0, y= 0}, o=false}, {pos={x=-1, y= 1}, o=false}, {pos={x=-1, y= 2}, o=false},
    {pos={x=-1, y= 3}, o=false}}
curved_rail[1][-1] = {
    {pos={x= 1, y=-4}, o= true}, {pos={x= 1, y=-3}, o=false}, {pos={x= 0, y=-3}, o=false},
    {pos={x= 0, y=-2}, o=false}, {pos={x=-1, y=-1}, o=false}, {pos={x=-1, y= 0}, o=false},
    {pos={x=-2, y= 1}, o=false}, {pos={x=-2, y= 2}, o=false}, {pos={x=-2, y= 3}, o=false}}
curved_rail[1][-2] = {
    {pos={x= 0, y=-4}, o=false}, {pos={x=-1, y=-3}, o=false}, {pos={x=-1, y=-2}, o=false},
    {pos={x=-2, y=-2}, o=false}, {pos={x=-2, y=-1}, o=false}, {pos={x=-2, y= 0}, o=false},
    {pos={x=-3, y= 1}, o=false}, {pos={x=-3, y= 2}, o=false}, {pos={x=-3, y= 3}, o=false}}
curved_rail[1][-3] = {
    {pos={x= 0, y=-5}, o= true}, {pos={x=-1, y=-5}, o=false}, {pos={x=-1, y=-4}, o=false},
    {pos={x=-2, y=-4}, o=false}, {pos={x=-2, y=-3}, o=false}, {pos={x=-3, y=-2}, o=false},
    {pos={x=-3, y=-1}, o=false}, {pos={x=-3, y= 0}, o=false}, {pos={x=-4, y= 0}, o=false},
    {pos={x=-4, y= 1}, o=false}, {pos={x=-4, y= 2}, o=false}, {pos={x=-4, y= 3}, o=false}}
curved_rail[1][-4] = {
    {pos={x=-1, y=-6}, o= true}, {pos={x=-2, y=-5}, o=false}, {pos={x=-3, y=-4}, o=false},
    {pos={x=-3, y=-3}, o=false}, {pos={x=-4, y=-2}, o=false}, {pos={x=-4, y=-1}, o=false},
    {pos={x=-5, y= 0}, o=false}, {pos={x=-5, y= 1}, o=false}, {pos={x=-5, y= 2}, o=false},
    {pos={x=-5, y= 3}, o=false}}
curved_rail[1][-5] = {
    {pos={x=-2, y=-7}, o= true}, {pos={x=-2, y=-6}, o=false}, {pos={x=-3, y=-5}, o=false},
    {pos={x=-4, y=-4}, o=false}, {pos={x=-4, y=-3}, o=false}, {pos={x=-5, y=-2}, o=false},
    {pos={x=-5, y=-1}, o=false}, {pos={x=-6, y= 0}, o=false}, {pos={x=-6, y= 1}, o=false},
    {pos={x=-6, y= 2}, o=false}, {pos={x=-6, y= 3}, o=false}}
curved_rail[1][-6] = {
    {pos={x=-3, y=-7}, o=false}, {pos={x=-3, y=-6}, o=false}, {pos={x=-4, y=-6}, o=false},
    {pos={x=-4, y=-5}, o=false}, {pos={x=-5, y=-4}, o=false}, {pos={x=-5, y=-3}, o=false},
    {pos={x=-6, y=-3}, o=false}, {pos={x=-6, y=-2}, o=false}, {pos={x=-6, y=-1}, o=false},
    {pos={x=-7, y= 0}, o=false}, {pos={x=-7, y= 1}, o=false}, {pos={x=-7, y= 2}, o=false},
    {pos={x=-7, y= 3}, o=false}}
curved_rail[1][-7] = {
    {pos={x=-3, y=-8}, o= true}, {pos={x=-4, y=-7}, o=false}, {pos={x=-5, y=-6}, o=false},
    {pos={x=-5, y=-5}, o=false}, {pos={x=-6, y=-5}, o=false}, {pos={x=-6, y=-4}, o=false},
    {pos={x=-7, y=-3}, o=false}, {pos={x=-7, y=-2}, o=false}, {pos={x=-7, y=-1}, o=false},
    {pos={x=-8, y= 0}, o=false}, {pos={x=-8, y= 1}, o=false}, {pos={x=-8, y= 2}, o=false},
    {pos={x=-8, y= 3}, o=false}}
curved_rail[1][-8] = {
    {pos={x=-4, y=-9}, o= true}, {pos={x=-4, y=-8}, o=false}, {pos={x=-5, y=-8}, o=false},
    {pos={x=-5, y=-7}, o=false}, {pos={x=-6, y=-7}, o=false}, {pos={x=-6, y=-6}, o=false},
    {pos={x=-7, y=-5}, o=false}, {pos={x=-7, y=-4}, o=false}, {pos={x=-8, y=-3}, o=false},
    {pos={x=-8, y=-2}, o=false}, {pos={x=-8, y=-1}, o=false}, {pos={x=-9, y= 0}, o=false},
    {pos={x=-9, y= 1}, o=false}, {pos={x=-9, y= 2}, o=false}, {pos={x=-9, y= 3}, o=false}}
-- ======================================
curved_rail[2] = {}
curved_rail[2][8] = {
    {pos={x= 8, y= 3}, o= true}, {pos={x= 7, y= 3}, o=false}, {pos={x= 7, y= 4}, o=false},
    {pos={x= 6, y= 4}, o=false}, {pos={x= 6, y= 5}, o=false}, {pos={x= 5, y= 5}, o=false},
    {pos={x= 4, y= 6}, o=false}, {pos={x= 3, y= 6}, o=false}, {pos={x= 2, y= 7}, o=false},
    {pos={x= 1, y= 7}, o=false}, {pos={x= 0, y= 7}, o=false}, {pos={x=-1, y= 8}, o=false},
    {pos={x=-2, y= 8}, o=false}, {pos={x=-3, y= 8}, o=false}, {pos={x=-4, y= 8}, o=false}}
curved_rail[2][7] = {
    {pos={x= 7, y= 2}, o= true}, {pos={x= 6, y= 3}, o=false}, {pos={x= 5, y= 4}, o=false},
    {pos={x= 4, y= 4}, o=false}, {pos={x= 4, y= 5}, o=false}, {pos={x= 3, y= 5}, o=false},
    {pos={x= 2, y= 6}, o=false}, {pos={x= 1, y= 6}, o=false}, {pos={x= 0, y= 6}, o=false},
    {pos={x=-1, y= 7}, o=false}, {pos={x=-2, y= 7}, o=false}, {pos={x=-3, y= 7}, o=false},
    {pos={x=-4, y= 7}, o=false}}
curved_rail[2][6] = {
    {pos={x= 6, y= 2}, o=false}, {pos={x= 5, y= 2}, o=false}, {pos={x= 5, y= 3}, o=false},
    {pos={x= 4, y= 3}, o=false}, {pos={x= 3, y= 4}, o=false}, {pos={x= 2, y= 4}, o=false},
    {pos={x= 2, y= 5}, o=false}, {pos={x= 1, y= 5}, o=false}, {pos={x= 0, y= 5}, o=false},
    {pos={x=-1, y= 6}, o=false}, {pos={x=-2, y= 6}, o=false}, {pos={x=-3, y= 6}, o=false},
    {pos={x=-4, y= 6}, o=false}}
curved_rail[2][5] = {
    {pos={x= 6, y= 1}, o= true}, {pos={x= 5, y= 1}, o=false}, {pos={x= 4, y= 2}, o=false},
    {pos={x= 3, y= 3}, o=false}, {pos={x= 2, y= 3}, o=false}, {pos={x= 1, y= 4}, o=false},
    {pos={x= 0, y= 4}, o=false}, {pos={x=-1, y= 5}, o=false}, {pos={x=-2, y= 5}, o=false},
    {pos={x=-3, y= 5}, o=false}, {pos={x=-4, y= 5}, o=false}}
curved_rail[2][4] = {
    {pos={x= 5, y= 0}, o= true}, {pos={x= 4, y= 1}, o=false}, {pos={x= 3, y= 2}, o=false},
    {pos={x= 2, y= 2}, o=false}, {pos={x= 1, y= 3}, o=false}, {pos={x= 0, y= 3}, o=false},
    {pos={x=-1, y= 4}, o=false}, {pos={x=-2, y= 4}, o=false}, {pos={x=-3, y= 4}, o=false},
    {pos={x=-4, y= 4}, o=false}}
curved_rail[2][3] = {
    {pos={x= 4, y=-1}, o= true}, {pos={x= 4, y= 0}, o=false}, {pos={x= 3, y= 0}, o=false},
    {pos={x= 3, y= 1}, o=false}, {pos={x= 2, y= 1}, o=false}, {pos={x= 1, y= 2}, o=false},
    {pos={x= 0, y= 2}, o=false}, {pos={x=-1, y= 2}, o=false}, {pos={x=-1, y= 3}, o=false},
    {pos={x=-2, y= 3}, o=false}, {pos={x=-3, y= 3}, o=false}, {pos={x=-4, y= 3}, o=false}}
curved_rail[2][2] = {
    {pos={x= 3, y=-1}, o=false}, {pos={x= 2, y= 0}, o=false}, {pos={x= 1, y= 0}, o=false},
    {pos={x= 1, y= 1}, o=false}, {pos={x= 0, y= 1}, o=false}, {pos={x=-1, y= 1}, o=false},
    {pos={x=-2, y= 2}, o=false}, {pos={x=-3, y= 2}, o=false}, {pos={x=-4, y= 2}, o=false}}
curved_rail[2][1] = {
    {pos={x= 3, y=-2}, o= true}, {pos={x= 2, y=-2}, o=false}, {pos={x= 2, y=-1}, o=false},
    {pos={x= 1, y=-1}, o=false}, {pos={x= 0, y= 0}, o=false}, {pos={x=-1, y= 0}, o=false},
    {pos={x=-2, y= 1}, o=false}, {pos={x=-3, y= 1}, o=false}, {pos={x=-4, y= 1}, o=false}}
curved_rail[2][-1] = {
    {pos={x= 2, y=-3}, o= true}, {pos={x= 1, y=-2}, o=false}, {pos={x= 0, y=-1}, o=false},
    {pos={x=-1, y=-1}, o=false}, {pos={x=-2, y= 0}, o=false}, {pos={x=-3, y= 0}, o=false},
    {pos={x=-4, y= 0}, o=false}}
curved_rail[2][-2] = {
    {pos={x= 1, y=-3}, o=false}, {pos={x= 0, y=-2}, o=false}, {pos={x=-1, y=-2}, o=false},
    {pos={x=-2, y=-1}, o=false}, {pos={x=-3, y=-1}, o=false}, {pos={x=-4, y=-1}, o=false}}
curved_rail[2][-3] = {
    {pos={x= 1, y=-4}, o= true}, {pos={x= 0, y=-4}, o=false}, {pos={x= 0, y=-3}, o=false},
    {pos={x=-1, y=-3}, o=false}, {pos={x=-2, y=-2}, o=false}, {pos={x=-3, y=-2}, o=false},
    {pos={x=-4, y=-2}, o=false}}
curved_rail[2][-4] = {
    {pos={x= 0, y=-5}, o= true}, {pos={x=-1, y=-4}, o=false}, {pos={x=-2, y=-4}, o=false},
    {pos={x=-2, y=-3}, o=false}, {pos={x=-3, y=-3}, o=false}, {pos={x=-4, y=-3}, o=false}}
curved_rail[2][-5] = {
    {pos={x=-1, y=-6}, o= true}, {pos={x=-1, y=-5}, o=false}, {pos={x=-2, y=-5}, o=false},
    {pos={x=-3, y=-4}, o=false}, {pos={x=-4, y=-4}, o=false}}
curved_rail[2][-6] = {
    {pos={x=-2, y=-6}, o=false}, {pos={x=-3, y=-5}, o=false}, {pos={x=-4, y=-5}, o=false}}
curved_rail[2][-7] = {
    {pos={x=-2, y=-7}, o= true}, {pos={x=-3, y=-6}, o=false}, {pos={x=-4, y=-6}, o=false}}
curved_rail[2][-8] = {
    {pos={x=-3, y=-8}, o= true}, {pos={x=-3, y=-7}, o=false}, {pos={x=-4, y=-7}, o=false}}
-- ======================================
curved_rail[3] = {}
curved_rail[3][8] = {
    {pos={x=-3, y= 7}, o= true}, {pos={x=-3, y= 6}, o=false}, {pos={x=-4, y= 6}, o=false}}
curved_rail[3][7] = {
    {pos={x=-2, y= 6}, o= true}, {pos={x=-3, y= 5}, o=false}, {pos={x=-4, y= 5}, o=false}}
curved_rail[3][6] = {
    {pos={x=-2, y= 5}, o=false}, {pos={x=-3, y= 4}, o=false}, {pos={x=-4, y= 4}, o=false}}
curved_rail[3][5] = {
    {pos={x=-1, y= 5}, o= true}, {pos={x=-1, y= 4}, o=false}, {pos={x=-2, y= 4}, o=false},
    {pos={x=-3, y= 3}, o=false}, {pos={x=-4, y= 3}, o=false}}
curved_rail[3][4] = {
    {pos={x= 0, y= 4}, o= true}, {pos={x=-1, y= 3}, o=false}, {pos={x=-2, y= 3}, o=false},
    {pos={x=-2, y= 2}, o=false}, {pos={x=-3, y= 2}, o=false}, {pos={x=-4, y= 2}, o=false}}
curved_rail[3][3] = {
    {pos={x= 1, y= 3}, o= true}, {pos={x= 0, y= 3}, o=false}, {pos={x= 0, y= 2}, o=false},
    {pos={x=-1, y= 2}, o=false}, {pos={x=-2, y= 1}, o=false}, {pos={x=-3, y= 1}, o=false},
    {pos={x=-4, y= 1}, o=false}}
curved_rail[3][2] = {
    {pos={x= 1, y= 2}, o=false}, {pos={x= 0, y= 1}, o=false}, {pos={x=-1, y= 1}, o=false},
    {pos={x=-2, y= 0}, o=false}, {pos={x=-3, y= 0}, o=false}, {pos={x=-4, y= 0}, o=false}}
curved_rail[3][1] = {
    {pos={x= 2, y= 2}, o= true}, {pos={x= 1, y= 1}, o=false}, {pos={x= 0, y= 0}, o=false},
    {pos={x=-1, y= 0}, o=false}, {pos={x=-2, y=-1}, o=false}, {pos={x=-3, y=-1}, o=false},
    {pos={x=-4, y=-1}, o=false}}
curved_rail[3][-1] = {
    {pos={x= 3, y= 1}, o= true}, {pos={x= 2, y= 1}, o=false}, {pos={x= 2, y= 0}, o=false},
    {pos={x= 1, y= 0}, o=false}, {pos={x= 0, y=-1}, o=false}, {pos={x=-1, y=-1}, o=false},
    {pos={x=-2, y=-2}, o=false}, {pos={x=-3, y=-2}, o=false}, {pos={x=-4, y=-2}, o=false}}
curved_rail[3][-2] = {
    {pos={x= 3, y= 0}, o=false}, {pos={x= 2, y=-1}, o=false}, {pos={x= 1, y=-1}, o=false},
    {pos={x= 1, y=-2}, o=false}, {pos={x= 0, y=-2}, o=false}, {pos={x=-1, y=-2}, o=false},
    {pos={x=-2, y=-3}, o=false}, {pos={x=-3, y=-3}, o=false}, {pos={x=-4, y=-3}, o=false}}
curved_rail[3][-3] = {
    {pos={x= 4, y= 0}, o= true}, {pos={x= 4, y=-1}, o=false}, {pos={x= 3, y=-1}, o=false},
    {pos={x= 3, y=-2}, o=false}, {pos={x= 2, y=-2}, o=false}, {pos={x= 1, y=-3}, o=false},
    {pos={x= 0, y=-3}, o=false}, {pos={x=-1, y=-3}, o=false}, {pos={x=-1, y=-4}, o=false},
    {pos={x=-2, y=-4}, o=false}, {pos={x=-3, y=-4}, o=false}, {pos={x=-4, y=-4}, o=false}}
curved_rail[3][-4] = {
    {pos={x= 5, y=-1}, o= true}, {pos={x= 4, y=-2}, o=false}, {pos={x= 3, y=-3}, o=false},
    {pos={x= 2, y=-3}, o=false}, {pos={x= 1, y=-4}, o=false}, {pos={x= 0, y=-4}, o=false},
    {pos={x=-1, y=-5}, o=false}, {pos={x=-2, y=-5}, o=false}, {pos={x=-3, y=-5}, o=false},
    {pos={x=-4, y=-5}, o=false}}
curved_rail[3][-5] = {
    {pos={x= 6, y=-2}, o= true}, {pos={x= 5, y=-2}, o=false}, {pos={x= 4, y=-3}, o=false},
    {pos={x= 3, y=-4}, o=false}, {pos={x= 2, y=-4}, o=false}, {pos={x= 1, y=-5}, o=false},
    {pos={x= 0, y=-5}, o=false}, {pos={x=-1, y=-6}, o=false}, {pos={x=-2, y=-6}, o=false},
    {pos={x=-3, y=-6}, o=false}, {pos={x=-4, y=-6}, o=false}}
curved_rail[3][-6] = {
    {pos={x= 6, y=-3}, o=false}, {pos={x= 5, y=-3}, o=false}, {pos={x= 5, y=-4}, o=false},
    {pos={x= 4, y=-4}, o=false}, {pos={x= 3, y=-5}, o=false}, {pos={x= 2, y=-5}, o=false},
    {pos={x= 2, y=-6}, o=false}, {pos={x= 1, y=-6}, o=false}, {pos={x= 0, y=-6}, o=false},
    {pos={x=-1, y=-7}, o=false}, {pos={x=-2, y=-7}, o=false}, {pos={x=-3, y=-7}, o=false},
    {pos={x=-4, y=-7}, o=false}}
curved_rail[3][-7] = {
    {pos={x= 7, y=-3}, o= true}, {pos={x= 6, y=-4}, o=false}, {pos={x= 5, y=-5}, o=false},
    {pos={x= 4, y=-5}, o=false}, {pos={x= 4, y=-6}, o=false}, {pos={x= 3, y=-6}, o=false},
    {pos={x= 2, y=-7}, o=false}, {pos={x= 1, y=-7}, o=false}, {pos={x= 0, y=-7}, o=false},
    {pos={x=-1, y=-8}, o=false}, {pos={x=-2, y=-8}, o=false}, {pos={x=-3, y=-8}, o=false},
    {pos={x=-4, y=-8}, o=false}}
curved_rail[3][-8] = {
    {pos={x= 8, y=-4}, o= true}, {pos={x= 7, y=-4}, o=false}, {pos={x= 7, y=-5}, o=false},
    {pos={x= 6, y=-5}, o=false}, {pos={x= 6, y=-6}, o=false}, {pos={x= 5, y=-6}, o=false},
    {pos={x= 4, y=-7}, o=false}, {pos={x= 3, y=-7}, o=false}, {pos={x= 2, y=-8}, o=false},
    {pos={x= 1, y=-8}, o=false}, {pos={x= 0, y=-8}, o=false}, {pos={x=-1, y=-9}, o=false},
    {pos={x=-2, y=-9}, o=false}, {pos={x=-3, y=-9}, o=false}, {pos={x=-4, y=-9}, o=false}}
-- ======================================
curved_rail[4] = {}
curved_rail[4][8] = {
    {pos={x=-4, y= 8}, o= true}, {pos={x=-4, y= 7}, o=false}, {pos={x=-5, y= 7}, o=false},
    {pos={x=-5, y= 6}, o=false}, {pos={x=-6, y= 6}, o=false}, {pos={x=-6, y= 5}, o=false},
    {pos={x=-7, y= 4}, o=false}, {pos={x=-7, y= 3}, o=false}, {pos={x=-8, y= 2}, o=false},
    {pos={x=-8, y= 1}, o=false}, {pos={x=-8, y= 0}, o=false}, {pos={x=-9, y=-1}, o=false},
    {pos={x=-9, y=-2}, o=false}, {pos={x=-9, y=-3}, o=false}, {pos={x=-9, y=-4}, o=false}}
curved_rail[4][7] = {
    {pos={x=-3, y= 7}, o= true}, {pos={x=-4, y= 6}, o=false}, {pos={x=-5, y= 5}, o=false},
    {pos={x=-5, y= 4}, o=false}, {pos={x=-6, y= 4}, o=false}, {pos={x=-6, y= 3}, o=false},
    {pos={x=-7, y= 2}, o=false}, {pos={x=-7, y= 1}, o=false}, {pos={x=-7, y= 0}, o=false},
    {pos={x=-8, y=-1}, o=false}, {pos={x=-8, y=-2}, o=false}, {pos={x=-8, y=-3}, o=false},
    {pos={x=-8, y=-4}, o=false}}
curved_rail[4][6] = {
    {pos={x=-3, y= 6}, o=false}, {pos={x=-3, y= 5}, o=false}, {pos={x=-4, y= 5}, o=false},
    {pos={x=-4, y= 4}, o=false}, {pos={x=-5, y= 3}, o=false}, {pos={x=-5, y= 2}, o=false},
    {pos={x=-6, y= 2}, o=false}, {pos={x=-6, y= 1}, o=false}, {pos={x=-6, y= 0}, o=false},
    {pos={x=-7, y=-1}, o=false}, {pos={x=-7, y=-2}, o=false}, {pos={x=-7, y=-3}, o=false},
    {pos={x=-7, y=-4}, o=false}}
curved_rail[4][5] = {
    {pos={x=-2, y= 6}, o= true}, {pos={x=-2, y= 5}, o=false}, {pos={x=-3, y= 4}, o=false},
    {pos={x=-4, y= 3}, o=false}, {pos={x=-4, y= 2}, o=false}, {pos={x=-5, y= 1}, o=false},
    {pos={x=-5, y= 0}, o=false}, {pos={x=-6, y=-1}, o=false}, {pos={x=-6, y=-2}, o=false},
    {pos={x=-6, y=-3}, o=false}, {pos={x=-6, y=-4}, o=false}}
curved_rail[4][4] = {
    {pos={x=-1, y= 5}, o= true}, {pos={x=-2, y= 4}, o=false}, {pos={x=-3, y= 3}, o=false},
    {pos={x=-3, y= 2}, o=false}, {pos={x=-4, y= 1}, o=false}, {pos={x=-4, y= 0}, o=false},
    {pos={x=-5, y=-1}, o=false}, {pos={x=-5, y=-2}, o=false}, {pos={x=-5, y=-3}, o=false},
    {pos={x=-5, y=-4}, o=false}}
curved_rail[4][3] = {
    {pos={x= 0, y= 4}, o= true}, {pos={x=-1, y= 4}, o=false}, {pos={x=-1, y= 3}, o=false},
    {pos={x=-2, y= 3}, o=false}, {pos={x=-2, y= 2}, o=false}, {pos={x=-3, y= 1}, o=false},
    {pos={x=-3, y= 0}, o=false}, {pos={x=-3, y=-1}, o=false}, {pos={x=-4, y=-1}, o=false},
    {pos={x=-4, y=-2}, o=false}, {pos={x=-4, y=-3}, o=false}, {pos={x=-4, y=-4}, o=false}}
curved_rail[4][2] = {
    {pos={x= 0, y= 3}, o=false}, {pos={x=-1, y= 2}, o=false}, {pos={x=-1, y= 1}, o=false},
    {pos={x=-2, y= 1}, o=false}, {pos={x=-2, y= 0}, o=false}, {pos={x=-2, y=-1}, o=false},
    {pos={x=-3, y=-2}, o=false}, {pos={x=-3, y=-3}, o=false}, {pos={x=-3, y=-4}, o=false}}
curved_rail[4][1] = {
    {pos={x= 1, y= 3}, o= true}, {pos={x= 1, y= 2}, o=false}, {pos={x= 0, y= 2}, o=false},
    {pos={x= 0, y= 1}, o=false}, {pos={x=-1, y= 0}, o=false}, {pos={x=-1, y=-1}, o=false},
    {pos={x=-2, y=-2}, o=false}, {pos={x=-2, y=-3}, o=false}, {pos={x=-2, y=-4}, o=false}}
curved_rail[4][-1] = {
    {pos={x= 2, y= 2}, o= true}, {pos={x= 1, y= 1}, o=false}, {pos={x= 0, y= 0}, o=false},
    {pos={x= 0, y=-1}, o=false}, {pos={x=-1, y=-2}, o=false}, {pos={x=-1, y=-3}, o=false},
    {pos={x=-1, y=-4}, o=false}}
curved_rail[4][-2] = {
    {pos={x= 2, y= 1}, o=false}, {pos={x= 1, y= 0}, o=false}, {pos={x= 1, y=-1}, o=false},
    {pos={x= 0, y=-2}, o=false}, {pos={x= 0, y=-3}, o=false}, {pos={x= 0, y=-4}, o=false}}
curved_rail[4][-3] = {
    {pos={x= 3, y= 1}, o= true}, {pos={x= 3, y= 0}, o=false}, {pos={x= 2, y= 0}, o=false},
    {pos={x= 2, y=-1}, o=false}, {pos={x= 1, y=-2}, o=false}, {pos={x= 1, y=-3}, o=false},
    {pos={x= 1, y=-4}, o=false}}
curved_rail[4][-4] = {
    {pos={x= 4, y= 0}, o= true}, {pos={x= 3, y=-1}, o=false}, {pos={x= 3, y=-2}, o=false},
    {pos={x= 2, y=-2}, o=false}, {pos={x= 2, y=-3}, o=false}, {pos={x= 2, y=-4}, o=false}}
curved_rail[4][-5] = {
    {pos={x= 5, y=-1}, o= true}, {pos={x= 4, y=-1}, o=false}, {pos={x= 4, y=-2}, o=false},
    {pos={x= 3, y=-3}, o=false}, {pos={x= 3, y=-4}, o=false}}
curved_rail[4][-6] = {
    {pos={x= 5, y=-2}, o=false}, {pos={x= 4, y=-3}, o=false}, {pos={x= 4, y=-4}, o=false}}
curved_rail[4][-7] = {
    {pos={x= 6, y=-2}, o= true}, {pos={x= 5, y=-3}, o=false}, {pos={x= 5, y=-4}, o=false}}
curved_rail[4][-8] = {
    {pos={x= 7, y=-3}, o= true}, {pos={x= 6, y=-3}, o=false}, {pos={x= 6, y=-4}, o=false}}
-- ======================================
curved_rail[5] = {}
curved_rail[5][8] = {
    {pos={x=-8, y=-3}, o= true}, {pos={x=-7, y=-3}, o=false}, {pos={x=-7, y=-4}, o=false}}
curved_rail[5][7] = {
    {pos={x=-7, y=-2}, o= true}, {pos={x=-6, y=-3}, o=false}, {pos={x=-6, y=-4}, o=false}}
curved_rail[5][6] = {
    {pos={x=-6, y=-2}, o=false}, {pos={x=-5, y=-3}, o=false}, {pos={x=-5, y=-4}, o=false}}
curved_rail[5][5] = {
    {pos={x=-6, y=-1}, o= true}, {pos={x=-5, y=-1}, o=false}, {pos={x=-5, y=-2}, o=false},
    {pos={x=-4, y=-3}, o=false}, {pos={x=-4, y=-4}, o=false}}
curved_rail[5][4] = {
    {pos={x=-5, y= 0}, o= true}, {pos={x=-4, y=-1}, o=false}, {pos={x=-4, y=-2}, o=false},
    {pos={x=-3, y=-2}, o=false}, {pos={x=-3, y=-3}, o=false}, {pos={x=-3, y=-4}, o=false}}
curved_rail[5][3] = {
    {pos={x=-4, y= 1}, o= true}, {pos={x=-4, y= 0}, o=false}, {pos={x=-3, y= 0}, o=false},
    {pos={x=-3, y=-1}, o=false}, {pos={x=-2, y=-2}, o=false}, {pos={x=-2, y=-3}, o=false},
    {pos={x=-2, y=-4}, o=false}}
curved_rail[5][2] = {
    {pos={x=-3, y= 1}, o=false}, {pos={x=-2, y= 0}, o=false}, {pos={x=-2, y=-1}, o=false},
    {pos={x=-1, y=-2}, o=false}, {pos={x=-1, y=-3}, o=false}, {pos={x=-1, y=-4}, o=false}}
curved_rail[5][1] = {
    {pos={x=-3, y= 2}, o= true}, {pos={x=-2, y= 1}, o=false}, {pos={x=-1, y= 0}, o=false},
    {pos={x=-1, y=-1}, o=false}, {pos={x= 0, y=-2}, o=false}, {pos={x= 0, y=-3}, o=false},
    {pos={x= 0, y=-4}, o=false}}
curved_rail[5][-1] = {
    {pos={x=-2, y= 3}, o= true}, {pos={x=-2, y= 2}, o=false}, {pos={x=-1, y= 2}, o=false},
    {pos={x=-1, y= 1}, o=false}, {pos={x= 0, y= 0}, o=false}, {pos={x= 0, y=-1}, o=false},
    {pos={x= 1, y=-2}, o=false}, {pos={x= 1, y=-3}, o=false}, {pos={x= 1, y=-4}, o=false}}
curved_rail[5][-2] = {
    {pos={x=-1, y= 3}, o=false}, {pos={x= 0, y= 2}, o=false}, {pos={x= 0, y= 1}, o=false},
    {pos={x= 1, y= 1}, o=false}, {pos={x= 1, y= 0}, o=false}, {pos={x= 1, y=-1}, o=false},
    {pos={x= 2, y=-2}, o=false}, {pos={x= 2, y=-3}, o=false}, {pos={x= 2, y=-4}, o=false}}
curved_rail[5][-3] = {
    {pos={x=-1, y= 4}, o= true}, {pos={x= 0, y= 4}, o=false}, {pos={x= 0, y= 3}, o=false},
    {pos={x= 1, y= 3}, o=false}, {pos={x= 1, y= 2}, o=false}, {pos={x= 2, y= 1}, o=false},
    {pos={x= 2, y= 0}, o=false}, {pos={x= 2, y=-1}, o=false}, {pos={x= 3, y=-1}, o=false},
    {pos={x= 3, y=-2}, o=false}, {pos={x= 3, y=-3}, o=false}, {pos={x= 3, y=-4}, o=false}}
curved_rail[5][-4] = {
    {pos={x= 0, y= 5}, o= true}, {pos={x= 1, y= 4}, o=false}, {pos={x= 2, y= 3}, o=false},
    {pos={x= 2, y= 2}, o=false}, {pos={x= 3, y= 1}, o=false}, {pos={x= 3, y= 0}, o=false},
    {pos={x= 4, y=-1}, o=false}, {pos={x= 4, y=-2}, o=false}, {pos={x= 4, y=-3}, o=false},
    {pos={x= 4, y=-4}, o=false}}
curved_rail[5][-5] = {
    {pos={x= 1, y= 6}, o= true}, {pos={x= 1, y= 5}, o=false}, {pos={x= 2, y= 4}, o=false},
    {pos={x= 3, y= 3}, o=false}, {pos={x= 3, y= 2}, o=false}, {pos={x= 4, y= 1}, o=false},
    {pos={x= 4, y= 0}, o=false}, {pos={x= 5, y=-1}, o=false}, {pos={x= 5, y=-2}, o=false},
    {pos={x= 5, y=-3}, o=false}, {pos={x= 5, y=-4}, o=false}}
curved_rail[5][-6] = {
    {pos={x= 2, y= 6}, o=false}, {pos={x= 2, y= 5}, o=false}, {pos={x= 3, y= 5}, o=false},
    {pos={x= 3, y= 4}, o=false}, {pos={x= 4, y= 3}, o=false}, {pos={x= 4, y= 2}, o=false},
    {pos={x= 5, y= 2}, o=false}, {pos={x= 5, y= 1}, o=false}, {pos={x= 5, y= 0}, o=false},
    {pos={x= 6, y=-1}, o=false}, {pos={x= 6, y=-2}, o=false}, {pos={x= 6, y=-3}, o=false},
    {pos={x= 6, y=-4}, o=false}}
curved_rail[5][-7] = {
    {pos={x= 2, y= 7}, o= true}, {pos={x= 3, y= 6}, o=false}, {pos={x= 4, y= 5}, o=false},
    {pos={x= 4, y= 4}, o=false}, {pos={x= 5, y= 4}, o=false}, {pos={x= 5, y= 3}, o=false},
    {pos={x= 6, y= 2}, o=false}, {pos={x= 6, y= 1}, o=false}, {pos={x= 6, y= 0}, o=false},
    {pos={x= 7, y=-1}, o=false}, {pos={x= 7, y=-2}, o=false}, {pos={x= 7, y=-3}, o=false},
    {pos={x= 7, y=-4}, o=false}}
curved_rail[5][-8] = {
    {pos={x= 3, y= 8}, o= true}, {pos={x= 3, y= 7}, o=false}, {pos={x= 4, y= 7}, o=false},
    {pos={x= 4, y= 6}, o=false}, {pos={x= 5, y= 6}, o=false}, {pos={x= 5, y= 5}, o=false},
    {pos={x= 6, y= 4}, o=false}, {pos={x= 6, y= 3}, o=false}, {pos={x= 7, y= 2}, o=false},
    {pos={x= 7, y= 1}, o=false}, {pos={x= 7, y= 0}, o=false}, {pos={x= 8, y=-1}, o=false},
    {pos={x= 8, y=-2}, o=false}, {pos={x= 8, y=-3}, o=false}, {pos={x= 8, y=-4}, o=false}}
-- ======================================
curved_rail[6] = {}
curved_rail[6][8] = {
    {pos={x=-9, y=-4}, o= true}, {pos={x=-8, y=-4}, o=false}, {pos={x=-8, y=-5}, o=false},
    {pos={x=-7, y=-5}, o=false}, {pos={x=-7, y=-6}, o=false}, {pos={x=-6, y=-6}, o=false},
    {pos={x=-5, y=-7}, o=false}, {pos={x=-4, y=-7}, o=false}, {pos={x=-3, y=-8}, o=false},
    {pos={x=-2, y=-8}, o=false}, {pos={x=-1, y=-8}, o=false}, {pos={x= 0, y=-9}, o=false},
    {pos={x= 1, y=-9}, o=false}, {pos={x= 2, y=-9}, o=false}, {pos={x= 3, y=-9}, o=false}}
curved_rail[6][7] = {
    {pos={x=-8, y=-3}, o= true}, {pos={x=-7, y=-4}, o=false}, {pos={x=-6, y=-5}, o=false},
    {pos={x=-5, y=-5}, o=false}, {pos={x=-5, y=-6}, o=false}, {pos={x=-4, y=-6}, o=false},
    {pos={x=-3, y=-7}, o=false}, {pos={x=-2, y=-7}, o=false}, {pos={x=-1, y=-7}, o=false},
    {pos={x= 0, y=-8}, o=false}, {pos={x= 1, y=-8}, o=false}, {pos={x= 2, y=-8}, o=false},
    {pos={x= 3, y=-8}, o=false}}
curved_rail[6][6] = {
    {pos={x=-7, y=-3}, o=false}, {pos={x=-6, y=-3}, o=false}, {pos={x=-6, y=-4}, o=false},
    {pos={x=-5, y=-4}, o=false}, {pos={x=-4, y=-5}, o=false}, {pos={x=-3, y=-5}, o=false},
    {pos={x=-3, y=-6}, o=false}, {pos={x=-2, y=-6}, o=false}, {pos={x=-1, y=-6}, o=false},
    {pos={x= 0, y=-7}, o=false}, {pos={x= 1, y=-7}, o=false}, {pos={x= 2, y=-7}, o=false},
    {pos={x= 3, y=-7}, o=false}}
curved_rail[6][5] = {
    {pos={x=-7, y=-2}, o= true}, {pos={x=-6, y=-2}, o=false}, {pos={x=-5, y=-3}, o=false},
    {pos={x=-4, y=-4}, o=false}, {pos={x=-3, y=-4}, o=false}, {pos={x=-2, y=-5}, o=false},
    {pos={x=-1, y=-5}, o=false}, {pos={x= 0, y=-6}, o=false}, {pos={x= 1, y=-6}, o=false},
    {pos={x= 2, y=-6}, o=false}, {pos={x= 3, y=-6}, o=false}}
curved_rail[6][4] = {
    {pos={x=-6, y=-1}, o= true}, {pos={x=-5, y=-2}, o=false}, {pos={x=-4, y=-3}, o=false},
    {pos={x=-3, y=-3}, o=false}, {pos={x=-2, y=-4}, o=false}, {pos={x=-1, y=-4}, o=false},
    {pos={x= 0, y=-5}, o=false}, {pos={x= 1, y=-5}, o=false}, {pos={x= 2, y=-5}, o=false},
    {pos={x= 3, y=-5}, o=false}}
curved_rail[6][3] = {
    {pos={x=-5, y= 0}, o= true}, {pos={x=-5, y=-1}, o=false}, {pos={x=-4, y=-1}, o=false},
    {pos={x=-4, y=-2}, o=false}, {pos={x=-3, y=-2}, o=false}, {pos={x=-2, y=-3}, o=false},
    {pos={x=-1, y=-3}, o=false}, {pos={x= 0, y=-3}, o=false}, {pos={x= 0, y=-4}, o=false},
    {pos={x= 1, y=-4}, o=false}, {pos={x= 2, y=-4}, o=false}, {pos={x= 3, y=-4}, o=false}}
curved_rail[6][2] = {
    {pos={x=-4, y= 0}, o=false}, {pos={x=-3, y=-1}, o=false}, {pos={x=-2, y=-1}, o=false},
    {pos={x=-2, y=-2}, o=false}, {pos={x=-1, y=-2}, o=false}, {pos={x= 0, y=-2}, o=false},
    {pos={x= 1, y=-3}, o=false}, {pos={x= 2, y=-3}, o=false}, {pos={x= 3, y=-3}, o=false}}
curved_rail[6][1] = {
    {pos={x=-4, y= 1}, o= true}, {pos={x=-3, y= 1}, o=false}, {pos={x=-3, y= 0}, o=false},
    {pos={x=-2, y= 0}, o=false}, {pos={x=-1, y=-1}, o=false}, {pos={x= 0, y=-1}, o=false},
    {pos={x= 1, y=-2}, o=false}, {pos={x= 2, y=-2}, o=false}, {pos={x= 3, y=-2}, o=false}}
curved_rail[6][-1] = {
    {pos={x=-3, y= 2}, o= true}, {pos={x=-2, y= 1}, o=false}, {pos={x=-1, y= 0}, o=false},
    {pos={x= 0, y= 0}, o=false}, {pos={x= 1, y=-1}, o=false}, {pos={x= 2, y=-1}, o=false},
    {pos={x= 3, y=-1}, o=false}}
curved_rail[6][-2] = {
    {pos={x=-2, y= 2}, o=false}, {pos={x=-1, y= 1}, o=false}, {pos={x= 0, y= 1}, o=false},
    {pos={x= 1, y= 0}, o=false}, {pos={x= 2, y= 0}, o=false}, {pos={x= 3, y= 0}, o=false}}
curved_rail[6][-3] = {
    {pos={x=-2, y= 3}, o= true}, {pos={x=-1, y= 3}, o=false}, {pos={x=-1, y= 2}, o=false},
    {pos={x= 0, y= 2}, o=false}, {pos={x= 1, y= 1}, o=false}, {pos={x= 2, y= 1}, o=false},
    {pos={x= 3, y= 1}, o=false}}
curved_rail[6][-4] = {
    {pos={x=-1, y= 4}, o= true}, {pos={x= 0, y= 3}, o=false}, {pos={x= 1, y= 3}, o=false},
    {pos={x= 1, y= 2}, o=false}, {pos={x= 2, y= 2}, o=false}, {pos={x= 3, y= 2}, o=false}}
curved_rail[6][-5] = {
    {pos={x= 0, y= 5}, o= true}, {pos={x= 0, y= 4}, o=false}, {pos={x= 1, y= 4}, o=false},
    {pos={x= 2, y= 3}, o=false}, {pos={x= 3, y= 3}, o=false}}
curved_rail[6][-6] = {
    {pos={x= 1, y= 5}, o=false}, {pos={x= 2, y= 4}, o=false}, {pos={x= 3, y= 4}, o=false}}
curved_rail[6][-7] = {
    {pos={x= 1, y= 6}, o= true}, {pos={x= 2, y= 5}, o=false}, {pos={x= 3, y= 5}, o=false}}
curved_rail[6][-8] = {
    {pos={x= 2, y= 7}, o= true}, {pos={x= 2, y= 6}, o=false}, {pos={x= 3, y= 6}, o=false}}
-- ======================================
curved_rail[7] = {}
curved_rail[7][8] = {
    {pos={x= 2, y=-8}, o= true}, {pos={x= 2, y=-7}, o=false}, {pos={x= 3, y=-7}, o=false}}
curved_rail[7][7] = {
    {pos={x= 1, y=-7}, o= true}, {pos={x= 2, y=-6}, o=false}, {pos={x= 3, y=-6}, o=false}}
curved_rail[7][6] = {
    {pos={x= 1, y=-6}, o=false}, {pos={x= 2, y=-5}, o=false}, {pos={x= 3, y=-5}, o=false}}
curved_rail[7][5] = {
    {pos={x= 0, y=-6}, o= true}, {pos={x= 0, y=-5}, o=false}, {pos={x= 1, y=-5}, o=false},
    {pos={x= 2, y=-4}, o=false}, {pos={x= 3, y=-4}, o=false}}
curved_rail[7][4] = {
    {pos={x=-1, y=-5}, o= true}, {pos={x= 0, y=-4}, o=false}, {pos={x= 1, y=-4}, o=false},
    {pos={x= 1, y=-3}, o=false}, {pos={x= 2, y=-3}, o=false}, {pos={x= 3, y=-3}, o=false}}
curved_rail[7][3] = {
    {pos={x=-2, y=-4}, o= true}, {pos={x=-1, y=-4}, o=false}, {pos={x=-1, y=-3}, o=false},
    {pos={x= 0, y=-3}, o=false}, {pos={x= 1, y=-2}, o=false}, {pos={x= 2, y=-2}, o=false},
    {pos={x= 3, y=-2}, o=false}}
curved_rail[7][2] = {
    {pos={x=-2, y=-3}, o=false}, {pos={x=-1, y=-2}, o=false}, {pos={x= 0, y=-2}, o=false},
    {pos={x= 1, y=-1}, o=false}, {pos={x= 2, y=-1}, o=false}, {pos={x= 3, y=-1}, o=false}}
curved_rail[7][1] = {
    {pos={x=-3, y=-3}, o= true}, {pos={x=-2, y=-2}, o=false}, {pos={x=-1, y=-1}, o=false},
    {pos={x= 0, y=-1}, o=false}, {pos={x= 1, y= 0}, o=false}, {pos={x= 2, y= 0}, o=false},
    {pos={x= 3, y= 0}, o=false}}
curved_rail[7][-1] = {
    {pos={x=-4, y=-2}, o= true}, {pos={x=-3, y=-2}, o=false}, {pos={x=-3, y=-1}, o=false},
    {pos={x=-2, y=-1}, o=false}, {pos={x=-1, y= 0}, o=false}, {pos={x= 0, y= 0}, o=false},
    {pos={x= 1, y= 1}, o=false}, {pos={x= 2, y= 1}, o=false}, {pos={x= 3, y= 1}, o=false}}
curved_rail[7][-2] = {
    {pos={x=-4, y=-1}, o=false}, {pos={x=-3, y= 0}, o=false}, {pos={x=-2, y= 0}, o=false},
    {pos={x=-2, y= 1}, o=false}, {pos={x=-1, y= 1}, o=false}, {pos={x= 0, y= 1}, o=false},
    {pos={x= 1, y= 2}, o=false}, {pos={x= 2, y= 2}, o=false}, {pos={x= 3, y= 2}, o=false}}
curved_rail[7][-3] = {
    {pos={x=-5, y=-1}, o= true}, {pos={x=-5, y= 0}, o=false}, {pos={x=-4, y= 0}, o=false},
    {pos={x=-4, y= 1}, o=false}, {pos={x=-3, y= 1}, o=false}, {pos={x=-2, y= 2}, o=false},
    {pos={x=-1, y= 2}, o=false}, {pos={x= 0, y= 2}, o=false}, {pos={x= 0, y= 3}, o=false},
    {pos={x= 1, y= 3}, o=false}, {pos={x= 2, y= 3}, o=false}, {pos={x= 3, y= 3}, o=false}}
curved_rail[7][-4] = {
    {pos={x=-6, y= 0}, o= true}, {pos={x=-5, y= 1}, o=false}, {pos={x=-4, y= 2}, o=false},
    {pos={x=-3, y= 2}, o=false}, {pos={x=-2, y= 3}, o=false}, {pos={x=-1, y= 3}, o=false},
    {pos={x= 0, y= 4}, o=false}, {pos={x= 1, y= 4}, o=false}, {pos={x= 2, y= 4}, o=false},
    {pos={x= 3, y= 4}, o=false}}
curved_rail[7][-5] = {
    {pos={x=-7, y= 1}, o= true}, {pos={x=-6, y= 1}, o=false}, {pos={x=-5, y= 2}, o=false},
    {pos={x=-4, y= 3}, o=false}, {pos={x=-3, y= 3}, o=false}, {pos={x=-2, y= 4}, o=false},
    {pos={x=-1, y= 4}, o=false}, {pos={x= 0, y= 5}, o=false}, {pos={x= 1, y= 5}, o=false},
    {pos={x= 2, y= 5}, o=false}, {pos={x= 3, y= 5}, o=false}}
curved_rail[7][-6] = {
    {pos={x=-7, y= 2}, o=false}, {pos={x=-6, y= 2}, o=false}, {pos={x=-6, y= 3}, o=false},
    {pos={x=-5, y= 3}, o=false}, {pos={x=-4, y= 4}, o=false}, {pos={x=-3, y= 4}, o=false},
    {pos={x=-3, y= 5}, o=false}, {pos={x=-2, y= 5}, o=false}, {pos={x=-1, y= 5}, o=false},
    {pos={x= 0, y= 6}, o=false}, {pos={x= 1, y= 6}, o=false}, {pos={x= 2, y= 6}, o=false},
    {pos={x= 3, y= 6}, o=false}}
curved_rail[7][-7] = {
    {pos={x=-8, y= 2}, o= true}, {pos={x=-7, y= 3}, o=false}, {pos={x=-6, y= 4}, o=false},
    {pos={x=-5, y= 4}, o=false}, {pos={x=-5, y= 5}, o=false}, {pos={x=-4, y= 5}, o=false},
    {pos={x=-3, y= 6}, o=false}, {pos={x=-2, y= 6}, o=false}, {pos={x=-1, y= 6}, o=false},
    {pos={x= 0, y= 7}, o=false}, {pos={x= 1, y= 7}, o=false}, {pos={x= 2, y= 7}, o=false},
    {pos={x= 3, y= 7}, o=false}}
curved_rail[7][-8] = {
    {pos={x=-9, y= 3}, o= true}, {pos={x=-8, y= 3}, o=false}, {pos={x=-8, y= 4}, o=false},
    {pos={x=-7, y= 4}, o=false}, {pos={x=-7, y= 5}, o=false}, {pos={x=-6, y= 5}, o=false},
    {pos={x=-5, y= 6}, o=false}, {pos={x=-4, y= 6}, o=false}, {pos={x=-3, y= 7}, o=false},
    {pos={x=-2, y= 7}, o=false}, {pos={x=-1, y= 7}, o=false}, {pos={x= 0, y= 8}, o=false},
    {pos={x= 1, y= 8}, o=false}, {pos={x= 2, y= 8}, o=false}, {pos={x= 3, y= 8}, o=false}}
-- ======================================
masks["curved-rail"] = curved_rail
masks["straight-rail"] = straight_rail

return masks
